name: Docker React App
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Code
        uses: actions/checkout@v3
      #- name: Install Node v18
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: 18
      - name: Install
        run: npm install
      - name: Test
        run: npm run test