name: Docker with Dockerfile React App
permissions:
  contents: write
on:
  workflow_dispatch:
runs:
  using: 'docker'
  image: 'Dockerfile'
jobs:
  php-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Exec PHP Script
        run: php ./script.php
        with:
          context: .
          file: ./Dockerfile
          push: true